spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/userdb
    username: postgres
    password: jasson
  flyway:
    enabled: true
    baseline-on-migrate: true

  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: jgualguanguzman@gmail.com
      password: wafk aotw qicx pcpx
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true